# Generated by Django 4.1.2 on 2022-10-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=60, verbose_name='Modelo'),
        ),
    ]
