# Generated by Django 4.1.2 on 2022-10-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auto', '0002_alter_auto_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometraje', models.PositiveSmallIntegerField(verbose_name='Kilometraje')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('costo', models.PositiveSmallIntegerField(verbose_name='Costo')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('auto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auto.auto')),
            ],
        ),
    ]
