# Generated by Django 4.1.2 on 2022-10-13 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mantenimiento',
            options={'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
    ]
